export const FETCH_WEATHER_LOADING = 'FETCH_WEATHER_LOADING';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const FETCH_WEATHER_NOT_FOUND = 'FETCH_WEATHER_NOT_FOUND';
